### ISSUE TITLE
NOW as time doesn't work

### ISSUE THREAD

**Issue by developer99** [treffynnon/PHP-at-Job-Queue-Wrapper#1]
Hi,

Isn't NOW for a time spec supposed to be valid to run the AT job right when it is submitted?  My research shows that it is.  But it seems that NOW+1min works but NOW does not work as At::cmd() returns a 0.

Thanks.

**Comment by treffynnon** [comment]
NOW is not valid for `at` as it runs every minute. You must therefore queue it to be run at the next interval now+1.
