### ISSUE TITLE
Split all classes to one by one PHP file

### ISSUE THREAD

**Issue by peter279k** [treffynnon/PHP-at-Job-Queue-Wrapper#10]
As title, it should be nice to split all PHP classes to standalone PHP files.

It can be also compatible with `PSR-4` autoloading because the `PSR-0` autoloading is deprecated.

**Comment by treffynnon** [comment]
I've not used this library myself for a good number of years now. I was part way through a version 2 about four years or so ago that would have been split up etc. 

Sorry to say though that the code I was working on will never be released as I've far too many other projects on my plate. I don't have time to write a new major version of a library that I don't use and will probably never have cause to use again.

Please fork the code or submit pull requests if the current state of the library does not match up to your requirements.

**Comment by peter279k** [comment]
> I've not used this library myself for a good number of years now. I was part way through a version 2 about four years or so ago that would have been split up etc.
> 
> Sorry to say though that the code I was working on will never be released as I've far too many other projects on my plate. I don't have time to write a new major version of a library that I don't use and will probably never have cause to use again.
> 
> Please fork the code or submit pull requests if the current state of the library does not match up to your requirements.

@treffynnon, thanks for your reply. Never mind.

I think you can choose one of following ways to resolve this issue and keep this repository continuous:

- I fork this repository and I maintain my forked repository. And please add some comments to notice this repository is migrated to my forked repo.
- Let me be one of collaborator on this repository.

What do you think about that? Thanks.

**Comment by treffynnon** [comment]
Good idea. I have added you as a collaborator on this repository. :)

**Comment by peter279k** [comment]
Thanks! @treffynnon :).
