### ISSUE TITLE
Queue regex does not match when username contains a hyphen

### ISSUE THREAD

**Issue by samgiety** [treffynnon/PHP-at-Job-Queue-Wrapper#2]
Suggested fix:

``` php
private static $queueRegex = '/^(\d+)\s+([\w\d- :]+) (\w) ([\w-]+)$/';
```

See [Portable Filename Character Set](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_278).

**Comment by treffynnon** [comment]
Thank you for the bug report - fixed in commit 346dc75a39c and release 1.0.1
