### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by johnathanmiller** [treffynnon/PHP-at-Job-Queue-Wrapper#7]
I'm testing this locally on a Mac. I get a **Fatal error:** The job has not been sucessfully added to the queue.

I did the run-script test and it failed. I tested it on Ubuntu and it succeeded.

What's the best way to get this working on macos? I did try altering the regex and it passed in a regex tester. I'm not the best with regex so I'm not too sure if it's incorrect or if I need to do anything else.

**Comment by treffynnon** [comment]
Can you add jobs manually using `at` directly in the terminal? After you
see that error can you see the job in the at queue (again, using `at` on
the command line to check)?

Could you include the test failure  messages please?

**Comment by johnathanmiller** [comment]
Disregard the issue, it was a mistake on my end with date time formatting. I reverted the regex back to the original and it works. Thanks for the prompt response!
