### ISSUE TITLE
Any release date for v2 ?

### ISSUE THREAD

**Issue by deba12** [treffynnon/PHP-at-Job-Queue-Wrapper#8]

**Comment by treffynnon** [comment]
I am not really working with PHP any more and I've not touched the code for
this lib in years. Unless someone else finishes it then, in practical
terms, there is no version two.

**Comment by deba12** [comment]
okay 
thank you ;)

**Comment by peter279k** [comment]
> okay
> thank you ;)

V2 will be released soon :).
